// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "BraillePrint",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "BraillePrint",
            targets: ["AppModule"],
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .paper),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            additionalInfoPlistContentFilePath: "MoreInfo.plist"
            appCategory: .utilities
        )
    ],
    dependencies: [
        .package(url: "https://github.com/Bridge-NOONGIL/KorToBraille.git", "1.0.2"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "KorToBraille", package: "KorToBraille")
            ],
            path: ".",
            exclude: ["./MoreInfo.plist"]
        )
    ]
)
